(function () {
  "use strict";
  const R=window.PixelPlanetRenderer,Z=window.PixelPlanetZip,builtin=window.PixelPlanetLocales;
  const $=id=>document.getElementById(id),state={language:"zh-CN",messages:builtin["zh-CN"],seedDirectories:{planet:null,galaxy:null},existingSeeds:{planet:new Set(),galaxy:new Set()},generated:{planet:null,galaxy:null},timers:{},usedSeeds:{planet:new Set(),galaxy:new Set()}};
  const colorLabels={planet:["sea1","sea2","land1","land2","land3","ring","frame","framePressed","frameDisabled"],galaxy:["background1","background2","nebula1","nebula2","nebula3","star1","star2","star3"]};
  const colorDefaults={planet:["#143c78","#1e5aa0","#3c8c50","#8ca05a","#beaa6e","#00ffff",R.FRAME_COLORS.hover,R.FRAME_COLORS.pressed,R.FRAME_COLORS.disabled],galaxy:["#030410","#080e26","#2846a0","#5a8cdc","#a0beff","#7896dc","#bed2ff","#fff5dc"]};
  function text(key,vars={}){let value=state.messages[key]??builtin["zh-CN"][key]??key;for(const[k,v]of Object.entries(vars))value=value.replaceAll(`{${k}}`,v);return value}
  function allLocales(){return builtin}
  function applyLanguage(code){const locales=allLocales();state.language=locales[code]?code:"zh-CN";state.messages=locales[state.language];document.documentElement.lang=state.language;document.querySelectorAll("[data-i18n]").forEach(el=>{el.textContent=text(el.dataset.i18n)});document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{el.placeholder=text(el.dataset.i18nPlaceholder)});const select=$("language-select");select.textContent="";Object.entries(locales).forEach(([id,m])=>{const option=document.createElement("option");option.value=id;option.textContent=m["language.name"]||id;select.append(option)});select.value=state.language;try{localStorage.setItem("ppg-language",state.language)}catch{}renderNamedOptions();updateDownloadLabels();["planet","galaxy"].forEach(updateSeedMode)}
  function renderNamedOptions(){const planet=$("planet-style"),galaxy=$("galaxy-theme"),pv=planet.value||"earth",gv=galaxy.value||"deep_blue";planet.textContent="";[...Object.keys(R.PALETTES),"custom"].forEach(id=>planet.add(new Option(text(`style.${id}`),id)));galaxy.textContent="";[...Object.keys(R.THEMES),"custom"].forEach(id=>galaxy.add(new Option(text(`theme.${id}`),id)));planet.value=pv;galaxy.value=gv}
  function pressedColor(hex){const value=parseInt(hex.slice(1),16),channel=(shift,extra=0)=>Math.max(0,Math.round(((value>>shift)&255)*.75)-extra).toString(16).padStart(2,"0");return`#${channel(16)}${channel(8,60)}${channel(0,60)}`}
  function buildColors(kind){const box=$(`${kind}-colors`);colorLabels[kind].forEach((name,i)=>{const label=document.createElement("label");label.className="color-field";label.dataset.colorName=name;const span=document.createElement("span");span.textContent=text(`custom.${name}`);span.dataset.i18n=`custom.${name}`;const input=document.createElement("input");input.type="color";input.name=`color-${name}`;input.value=colorDefaults[kind][i];input.addEventListener("input",()=>{if(kind==="planet"&&name==="frame"){const pressed=$("planet-form").elements["color-framePressed"];if(!pressed.dataset.userSet)pressed.value=pressedColor(input.value)}if(kind==="planet"&&name==="framePressed")input.dataset.userSet="true";$(kind==="planet"?"planet-style":"galaxy-theme").value="custom"});label.append(span,input);box.append(label)})}
  function randomSeed(){return crypto.getRandomValues(new Uint32Array(1))[0]&0x7fffffff}
  function resolveSeeds(kind,form){
    if(form.elements["seed-source"].value==="random")return{seeds:[randomSeed()],skipped:0};
    if(form.elements["seed-policy"].value==="reproduce"){const value=form.elements.seeds.value.split(",")[0].trim();if(!value)throw new Error("seed.required");if(!/^\d+$/.test(value)||Number(value)>2147483647)throw new Error("seed.invalidSingle");return{seeds:[Number(value)],skipped:0}}
    const parts=form.elements.seeds.value.split(",").map(value=>value.trim()).filter(Boolean);if(parts.some(value=>!/^\d+$/.test(value)||Number(value)>2147483647))throw new Error("seed.invalid");
    const blocked=new Set([...state.usedSeeds[kind],...parts.map(Number)]);let seed=randomSeed(),attempts=0;while(blocked.has(seed)&&attempts++<1000)seed=randomSeed();if(blocked.has(seed)){seed=0;while(blocked.has(seed)&&seed<2147483647)seed++}if(blocked.has(seed))throw new Error("seed.noAvailable");return{seeds:[seed],skipped:0};
  }
  function seedFromDefaultName(name,kind){const match=name.match(/-(\d+)(?:\.png|\.zip)?$/i);if(!match)return null;const seed=Number(match[1]),stem=name.replace(/(?:\.png|\.zip)$/i,""),prefix=stem.slice(0,-match[1].length-1),labels=[...Object.keys(kind==="planet"?R.PALETTES:R.THEMES),"custom"],valid=labels.includes(prefix)||labels.some(label=>prefix===`${kind}_animation-${label}`);return valid&&seed<=2147483647?seed:null}
  function pathKind(parts){for(const part of parts){const name=part.toLowerCase();if(name==="planet"||name==="planet_animation")return"planet";if(name==="galaxy"||name==="galaxy_animation")return"galaxy"}return null}
  async function collectExistingSeeds(handle,kind,parts=[],found=new Set()){const rootSeed=seedFromDefaultName(handle.name,kind);if(rootSeed!==null&&(!pathKind(parts)||pathKind(parts)===kind))found.add(rootSeed);try{for await(const[name,entry]of handle.entries()){const next=[...parts,name],entryKind=pathKind(next),seed=seedFromDefaultName(name,kind);if(seed!==null&&(!entryKind||entryKind===kind))found.add(seed);if(entry.kind==="directory")await collectExistingSeeds(entry,kind,next,found)}}catch(error){if(!parts.length)throw error}return found}
  async function ensureReadPermission(handle){if(!handle)return false;if(!handle.queryPermission)return true;const options={mode:"read"};if(await handle.queryPermission(options)==="granted")return true;return await handle.requestPermission(options)==="granted"}
  async function refreshExistingSeeds(kind){const handle=state.seedDirectories[kind];if(!handle)throw new Error("seed.folderRequired");if(!await ensureReadPermission(handle))throw new Error("seed.scanPermission");try{state.existingSeeds[kind]=await collectExistingSeeds(handle,kind);$(`${kind}-form`).elements.seeds.value=[...state.existingSeeds[kind]].sort((a,b)=>a-b).join(",");updateSeedScanStatus(kind);return state.existingSeeds[kind]}catch(error){if(error.message?.startsWith("seed."))throw error;throw new Error("seed.scanFailed")}}
  function canvasBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("PNG encoding failed")),"image/png"))}
  function cloneCanvas(source){const c=document.createElement("canvas");c.width=source.width;c.height=source.height;c.getContext("2d").drawImage(source,0,0);return c}
  function customPlanet(form){const values=colorLabels.planet.map(n=>form.elements[`color-${n}`].value);return{sea:values.slice(0,2),land:values.slice(2,5),ring:values[5],frame:values[6],framePressed:values[7],frameDisabled:values[8]}}
  function customGalaxy(form){const v=colorLabels.galaxy.map(n=>form.elements[`color-${n}`].value);return{top:v[0],bottom:v[1],nebula:v.slice(2,5),stars:v.slice(5,8)}}
  function stopPreview(kind){if(state.timers[kind])clearInterval(state.timers[kind]);state.timers[kind]=null}
  function previewFrames(kind,frames){stopPreview(kind);if(!frames.length)return;let index=0,canvas=$(`${kind}-canvas`),draw=()=>{canvas.width=frames[index].canvas.width;canvas.height=frames[index].canvas.height;canvas.getContext("2d").drawImage(frames[index].canvas,0,0)};draw();if(frames.length<2)return;state.timers[kind]=setInterval(()=>{index=(index+1)%frames.length;draw()},100)}
  function setBusy(kind,busy){const form=$(`${kind}-form`);form.querySelector('button[type="submit"]').disabled=busy;$(`${kind}-status`).textContent=text(busy?"status.generating":"status.ready")}
  async function generate(kind,form){
    stopPreview(kind);state.generated[kind]=null;$(`${kind}-download`).disabled=true;setBusy(kind,true);const mode=form.elements.mode.value,count=mode==="animation"?Math.max(15,Math.min(60,Number(form.elements.frames.value)||24)):1,canvas=$(`${kind}-canvas`),buttonStates=kind==="planet"&&form.elements.frame.checked&&form.elements["frame-states"].checked,reproduceMode=form.elements["seed-source"].value==="input"&&form.elements["seed-policy"].value==="reproduce",includePlain=buttonStates&&!reproduceMode;
    try{
      const resolved=resolveSeeds(kind,form),batches=[];let label;
      for(const seed of resolved.seeds){
        let options;if(kind==="planet"){const style=form.elements.style.value;label=style;options={size:Math.max(48,Math.min(192,Number(form.elements.size.value)||96)),scale:Math.max(1,Math.min(8,Number(form.elements.scale.value)||4)),seed,style,oceanRatio:Number(form.elements["ocean-ratio"].value),ring:form.elements.ring.checked,frame:form.elements.frame.checked,palette:style==="custom"?customPlanet(form):null}}
        else{const theme=form.elements.theme.value;label=theme;options={width:Math.max(64,Math.min(1024,Number(form.elements.width.value)||256)),height:Math.max(64,Math.min(1024,Number(form.elements.height.value)||256)),starRatio:Number(form.elements["star-ratio"].value),seed,theme,seamless:form.elements.seamless.value,spiral:form.elements.spiral.checked,themeData:theme==="custom"?customGalaxy(form):null}}
        const palette=kind==="planet"?(options.palette||R.PALETTES[options.style]):null,frameHover=palette?.frame||R.FRAME_COLORS.hover,stateVariants=buttonStates?[...(includePlain?[{id:"plain",color:null,frame:false}]:[]),{id:"hover",color:frameHover,frame:true},{id:"pressed",color:palette.framePressed||(palette.frame?pressedColor(frameHover):R.FRAME_COLORS.pressed),frame:true},{id:"disabled",color:palette.frameDisabled||R.FRAME_COLORS.disabled,frame:true}]:[{id:null,color:null,frame:options.frame}],frames=[],previewFrames=[];
        for(let i=0;i<count;i++){for(const variant of stateVariants){const renderOptions=variant.id?{...options,frame:variant.frame,frameColor:variant.color}:options;kind==="planet"?R.renderPlanet(canvas,renderOptions,i,count):R.renderGalaxy(canvas,renderOptions,i,count);const copy=cloneCanvas(canvas),blob=await canvasBlob(copy),frameName=`frame${String(i).padStart(3,"0")}.png`,name=count===1?(variant.id?`${label}-${seed}-${variant.id}.png`:`${label}-${seed}.png`):(variant.id?`${variant.id}/${frameName}`:frameName),file={canvas:copy,blob,name};frames.push(file);if(!variant.id||variant.id==="hover")previewFrames.push(file)}if(i%3===2)await new Promise(requestAnimationFrame)}
        batches.push({seed,frames,previewFrames});state.usedSeeds[kind].add(seed);
      }
      state.generated[kind]={kind,mode,seeds:resolved.seeds,label,batches,buttonStates,includePlain};const width=batches[0].frames[0].canvas.width,height=batches[0].frames[0].canvas.height;let resultKey=resolved.seeds.length===1?(count===1?"result.static":"result.animation"):(count===1?"result.multipleStatic":"result.multipleAnimation"),result=text(resultKey,{seed:resolved.seeds[0],count,width,height,seedCount:resolved.seeds.length,frameCount:count});if(buttonStates)result+=` · ${text(includePlain?"result.buttonStatesFour":"result.buttonStatesThree")}`;if(resolved.skipped)result+=` · ${text("result.skipped",{count:resolved.skipped})}`;$(`${kind}-status`).textContent=text("status.complete");$(`${kind}-result`).textContent=result;const button=$(`${kind}-download`);button.disabled=false;updateDownloadLabels();previewFrames(kind,batches.at(-1).previewFrames)
    }catch(error){const expectedSeedError=error.message?.startsWith("seed.");if(!expectedSeedError)console.error(error);$(`${kind}-status`).textContent=text(expectedSeedError?error.message:"status.failed");$(`${kind}-result`).textContent="";if(error.message==="seed.required"){alert(text("seed.required"));form.elements.seeds.focus()}}finally{form.querySelector('button[type="submit"]').disabled=false}
  }
  function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
  async function save(kind){const item=state.generated[kind];if(!item)return;let savedName;if(item.batches.length===1&&item.batches[0].frames.length===1){const file=item.batches[0].frames[0];downloadBlob(file.blob,file.name);savedName=file.name}else{const files=item.batches.flatMap(batch=>batch.frames.map(file=>({name:item.batches.length>1?`${item.label}-${batch.seed}/${file.name}`:file.name,blob:file.blob}))),zip=await Z.makeZip(files);savedName=item.batches.length>1?`${item.kind}-${item.label}-${item.batches.length}-seeds.zip`:item.mode==="animation"?`${item.kind}_animation-${item.label}-${item.batches[0].seed}.zip`:`${item.kind}-${item.label}-${item.batches[0].seed}-button-states.zip`;downloadBlob(zip,savedName)}$(`${kind}-status`).textContent=text("output.saved",{name:savedName})}
  function updateDownloadLabels(){["planet","galaxy"].forEach(kind=>{const item=state.generated[kind],button=$(`${kind}-download`),multipleStatic=item?.mode==="static"&&item.batches.some(batch=>batch.frames.length>1);button.textContent=text(item?.seeds?.length>1||multipleStatic?"common.downloadAll":item?.mode==="animation"?"common.downloadFrames":"common.download")})}
  function updateMode(kind){document.body.dataset[`mode${kind[0].toUpperCase()+kind.slice(1)}`]=$(`${kind}-form`).elements.mode.value}
  function updatePlanetEffectColors(){const form=$("planet-form"),frameEnabled=form.elements.frame.checked,stateColors=frameEnabled&&form.elements["frame-states"].checked;$("planet-frame-states-option").hidden=!frameEnabled;["ring","frame","framePressed","frameDisabled"].forEach(name=>{const field=$("planet-colors").querySelector(`[data-color-name="${name}"]`);if(field)field.hidden=name==="ring"?!form.elements.ring.checked:name==="frame"?!frameEnabled:!stateColors})}
  function updateSeedScanStatus(kind){const form=$(`${kind}-form`),handle=state.seedDirectories[kind],output=form.querySelector(".seed-scan-status");output.textContent=handle?text("seed.scanSummary",{folder:handle.name,count:state.existingSeeds[kind].size}):text("seed.scanDefault")}
  function updateSeedMode(kind){const form=$(`${kind}-form`),inputMode=form.elements["seed-source"].value==="input",avoid=inputMode&&form.elements["seed-policy"].value==="avoid",scan=form.elements["scan-existing"];form.querySelector(".seed-input-options").hidden=!inputMode;form.querySelector(".seed-scan-options").hidden=!avoid;form.querySelector(".seed-folder-controls").hidden=!scan.checked;form.elements.seeds.placeholder=avoid?text("seed.placeholder"):"";form.elements.seeds.closest("label").querySelector("span").textContent=text(avoid?"seed.avoidValues":"seed.value");updateSeedScanStatus(kind)}
  async function chooseSeedFolder(kind){if(!window.showDirectoryPicker){const form=$(`${kind}-form`);form.querySelector(".seed-scan-status").textContent=text("seed.scanUnsupported");return}try{state.seedDirectories[kind]=await window.showDirectoryPicker({id:`pixel-planet-seeds-${kind}`,mode:"read"});await refreshExistingSeeds(kind)}catch(error){if(error.name!=="AbortError")alert(text(error.message?.startsWith("seed.")?error.message:"seed.scanFailed"));updateSeedScanStatus(kind)}}
  function bind(){
    document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".tab,.generator-panel").forEach(e=>e.classList.remove("active"));tab.classList.add("active");$(tab.dataset.panel).classList.add("active")}));
    ["planet","galaxy"].forEach(kind=>{const form=$(`${kind}-form`);form.addEventListener("submit",event=>{event.preventDefault();generate(kind,form)});form.elements.mode.addEventListener("change",()=>updateMode(kind));form.elements["seed-source"].addEventListener("change",()=>updateSeedMode(kind));form.elements["seed-policy"].addEventListener("change",()=>updateSeedMode(kind));form.elements["scan-existing"].addEventListener("change",()=>updateSeedMode(kind));form.elements["choose-seed-folder"].addEventListener("click",()=>chooseSeedFolder(kind));$(`${kind}-download`).addEventListener("click",()=>save(kind));updateMode(kind);updateSeedMode(kind)});
    const planetForm=$("planet-form");["ring","frame","frame-states"].forEach(name=>planetForm.elements[name].addEventListener("change",updatePlanetEffectColors));updatePlanetEffectColors();
    $("language-select").addEventListener("change",e=>applyLanguage(e.target.value))
  }
  function init(){buildColors("planet");buildColors("galaxy");renderNamedOptions();bind();let language="zh-CN";try{language=localStorage.getItem("ppg-language")||language}catch{}applyLanguage(language);R.renderPlanet($("planet-canvas"),{size:96,scale:4,seed:731905,style:"earth",oceanRatio:60,ring:true,frame:false});R.renderGalaxy($("galaxy-canvas"),{width:256,height:256,starRatio:60,seed:731905,theme:"deep_blue",seamless:"none",spiral:false})}
  init();
})();
